name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 4.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  quiver: ^3.2.1
  path: ^1.9.0
  xml: ^6.5.0
  image: ^4.1.6
  collection: ^1.18.0

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
